### ISSUE TITLE
Cannot register 2 metrics with same name

### ISSUE THREAD

**Issue by Pratyush1991** [remicres/otbtf#28] opened 2020-07-16 08:25 UTC
Hello @remicres ,

I was trying to import OTB and TensorFlow via python. Looks like both cannot be imported or used at the same time either I have to use otb or TensorFlow separately. Is it because OTB uses the same library that is used by TensorFlow .?

As I understand I can create a separate python program to do tasks related to OTB and task related to TensorFlow and run them separately. Or should I import TensorFlow and call the OTB applications via the command line (os.subprocess).? (haven't tested this one tho)

Any suggestions.?

![image](https://user-images.githubusercontent.com/28738918/87645311-7b2ffe80-c777-11ea-9d28-518b5d5a04d0.png)

![image](https://user-images.githubusercontent.com/28738918/87645376-97cc3680-c777-11ea-80f9-fcdec21e688a.png)

**Comment by remicres** [comment] 2020-07-17 09:55
This reminds me of something. I encountered this issue in the early versions of otbtf. I did not really find the cause, but I did find a workaround at this time.

OTB needs an environment variable for the applications path (i.e. the `installed/lib/otb/applications/*` libraries files, `.so` under nux / `.dll` under windows I guess). In the beginning of OTB, I believe that the environment variable used was `ITK_AUTOLOAD_PATH`, but this changed later in `OTB_APPLICATION_PATH`. I did notice that, when I used the `ITK_AUTOLOAD_PATH`, the same error like yours happened. But after using only `OTB_APPLICATION_PATH`, I did avoid the error. I just checked with otbtf1.X, `python -c "import tensorflow; import otbApplication"` works fine. 

I think that this error happen in otbtf2.X. Can you confirm that?
I bet that if you unset  `OTB_APPLICATION_PATH`, you are able to import both tf and otb.
I don't know what is happening: it's like tf tries to initialize twice some component.

**Comment by remicres** [comment] 2020-07-17 09:59
I just give a try inside the otbtf2.0 and I can't reproduce your issue.
```
root@61276408e13f:/home/otbuser# python -c "import otbApplication; import tensorflow"
2020-07-17 09:58:05.757528: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
root@61276408e13f:/home/otbuser#
```

What is the version used?

**Comment by Pratyush1991** [comment] 2020-07-17 13:41
I have tried this on otbtf1.7:gpu as well as otbtf2.0:gpu. This one works for me as well `python -c "import tensorflow; import otbApplication"`. But the problem is when I call otb modules or tensorflow modules after import, it failed to work. Once it call any otb module then I cannot import TensorFlow vice versa.

Can you try these.? 

`python -c "import otbApplication; print(otbApplication.Registry_GetAvailableApplications()); import tensorflow; print(tensorflow.__version__)"`

`python -c " import tensorflow; import otbApplication; print(otbApplication.Registry_GetAvailableApplications())"`

**Comment by remicres** [comment] 2020-07-17 14:13
Damn, I can reproduce this bug. Indeed, in projects where I use both, I don't import tf and otb in the same `.py` file. I think that otbtf1.X is also impacted.

**Comment by lifeiteng** [comment] 2021-01-02 08:50
any progress？ I meet same error https://github.com/deepmind/reverb/pull/24

**Comment by remicres** [comment] 2021-01-04 08:48
Hi @lifeiteng , unfortunately not yet

**Comment by lifeiteng** [comment] 2021-01-04 10:37
> Hi @lifeiteng , unfortunately not yet

I have fixed it. Check the link options.

**Comment by remicres** [comment] 2021-01-04 18:21
Many thanks!

I am not sure to fully understand your fix though... I don't see what you do with the `PYTHON_LIB_PATH`, could you please detail a bit?

**Comment by lifeiteng** [comment] 2021-01-05 11:48
I will push the code ASAP.

> Many thanks!
> 
> I am not sure to fully understand your fix though... I don't see what you do with the `PYTHON_LIB_PATH`, could you please detail a bit?

I will push the code ASAP.

**Comment by lifeiteng** [comment] 2021-01-05 15:04
@remicres https://github.com/deepmind/reverb/pull/24/commits/1463007c84fc0a783b04e4f2bec3c7d4e1bdcabf FYI

**Comment by vidlb** [comment] 2021-01-18 19:43
@remicres @Pratyush1991  I found something interesting regarding : 
On my system I have /opt/otb and /opt/tensorflow . 
I can import otb (which I built against libtensorflow_cc )  without my TF env variables (PATH and LD_LIBRARY_PATH).

I tried the test command : 
`
import otbApplication  ;  print(otbApplication.Registry_GetAvailableApplications())`
`2021-01-18 20:09:44.499243: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0  
`
So even if I don't import tensorflow, it seems the TF lib is loaded anyway by OTB when I access any of the OTBTF app (but not with the other apps). So when we import otbApplication and tensorflow, it is loaded twice in memory, thus the protobuf error.

**Comment by remicres** [comment] 2021-01-19 15:17
Yes, it is something like that. I guess that the c++ tensorflow classes used in otb applications "triggers" something that is done twice if we also `import tensoflow` in python. I did not quite understood the fix that @lifeiteng did in deepmind/reverd, but it looks like it is a matter of the way to link tf libs...

**Comment by vidlb** [comment] 2021-01-19 15:31
The error looks the same but I don't think the problem is. I believe their issue was some executable in the project being linked to tensorflow while it wasn't required. I guess they fixed just by removing unnecessary links.
But since you need those apps linked to tf anyway, may be there's no solution: we just can't import both tf and OTBTF apps in the same process...

**Comment by vidlb** [comment] 2021-01-19 15:36
It would probably require to modify the TF core in order to avoid re-loading the lib if it was already loaded by OTB in the same python thread...

**Comment by remicres** [comment] 2021-01-19 15:38
For now, we can't import both, but that's a bit sad. It is like you couldn't import `otbApplication` and `gdal` in the same python code :sob:

**Comment by remicres** [comment] 2021-01-19 15:43
I am reading [this](https://github.com/google/or-tools/issues/1830#issuecomment-571579526). Do we have a way to know which version of protobuf is used from the OTB applications, and from the `import tensorflow` in python?

**Comment by vidlb** [comment] 2021-01-19 15:54
I also saw it yesterday. In the beginning I thought that could be the problem, if OTB was already using any other protobuf version (because of OpenCV may be ?).
But since we can import both tensorflow and any other otbApp (which isn't linked to tensorflow) without the protobuf error, I really think it is just because tf is loaded twice !

For the record TF2.4 is built with protobuf 3.14

**Comment by vidlb** [comment] 2021-01-19 18:21
May be https://github.com/tensorflow/tensorflow/issues/22810 , they're talking about building plugins with libtensorflow_cc.
They mentioned static lib and it seems hard to build, and I guest this is not an option with OTB modules architecture...

**Comment by remicres** [comment] 2021-01-19 19:49
> They mentioned static linking, it seems hard to build, and I guess that's not an option with the OTB module architecture...
I don't think that it is a limitation, but this would imply some cmake/c++ magic

**Comment by vidlb** [comment] 2021-01-19 20:09
Do you think it could work ? There's probably no way to be sure without trying...
But their error doesn't imply protobuf.

Also yesterday I tried something : 
After I realized libtensorflow_framework.so is already installed in the wheel, I thought this could be a reason if there are two libs and OTB did not compile with the same framework lib file.
So in a -dev container I tried to recompile with the file from the wheel instead of the one bazel produced.
Nope, same error.

But regarding the docker build may be we can remove this target from BZL_TARGETS and use the one installed in site-packages/

**Comment by vidlb** [comment] 2021-01-19 20:33
May be the problem is that you can't just import the tensorflow C and C++ instances in the same python thread ?
I don't know how it works in memory when otbApplication is loaded, but in theory libtensorflow.so is loaded with tf from python, and OTB will try to load libtensorflow_cc, but may be somehow bazel treat both libs the same way ?
So the `File already exists in database` would be the result of protobuf trying to create two instances of tensorflow using different libs, and/or just because both are name tensorflow in memory, because despite of the `_cc` suffix the namespace is still tensorflow.

**Comment by vidlb** [comment] 2021-01-19 20:41
I guess the best "fix" for now could be the `processing` python lib.

**Comment by vidlb** [comment] 2021-01-19 21:05
@Pratyush1991 I don't know if that will help you a lot but in fact you can import both tensorflow and every otb applications + otbPatchesSelection,   otbPatchesExtraction,  otbLabelImageSampleSelection and otbLabelImageSampleSelection in the same python script without the protobuf error.
It should occur only when using the TensorFlowModel* and *ClassifierFromDeepFeatures applications.
But since you're probably going to write your image and save your model in the disk, you could run a python script where you just run those things related to tf models with suprocess or directly via `os.system()`

**Comment by remicres** [comment] 2021-01-19 21:30
Nearly same issue [here](https://stackoverflow.com/questions/57617276/python-extension-module-using-tensorflow-c-api)

**Comment by vidlb** [comment] 2021-01-19 21:36
Wow, such a dead SO thread...
Well I really think [this comment](https://github.com/remicres/otbtf/issues/28#issuecomment-763119710)   is a good explanation.

**Comment by vidlb** [comment] 2021-01-19 21:43
But since TF is really low level may be just a BAD idea to load it twice in memory

**Comment by remicres** [comment] 2023-04-04 10:41
This 3 years old issue will be fixed in the otbtf 4.0.0 release

**Comment by vidlb** [comment] 2023-04-04 10:46
So..what kind of black magic did you invoke to make this work ?

**Comment by remicres** [comment] 2023-04-04 11:16
TBH I don't know if its the linking I did a bit differently, or moving to Tensorflow 2.12

**Comment by remicres** [comment] 2023-04-05 14:33
closed with r4.0.0

**Closed by remicres** 2023-04-05 14:33 UTC
Labels: bug
